# See: https://pre-commit.com/hooks.html
# For flake8 see: https://github.com/PyCQA/pyflakes/pull/457#issuecomment-555714836
repos:
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [
            '-e', 'git+https://github.com/pycqa/pyflakes@1911c20#egg=pyflakes',
            '-e', 'git+https://github.com/pycqa/pycodestyle@d219c68#egg=pycodestyle',
        ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: no-commit-to-branch
    - id: double-quote-string-fixer
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
      args: ['--max-line-length=88', '--ignore=W503,E402,E741']
